#' Create n sites sampled over t years
#'
#' This function creates for a given species pool, a data.frame of species observed per site and year.
#'
#' @param pool list, a list generated by sp_pool() containing species and ditrib
#' @param n_years Numeric, number of years
#' @param n_sites Numeric, number of sites (imagine a lattice)
#' @param rich_mean Numeric, mean species richness expected per site.
#' @param rich_sd Numeric, standard deviation of the species richness expected per site
#'
#' @return A data.frame.
#' @export
#'
#' @details Species are
#' assigned to each site randomly according to its expected distribution, ensuring
#' that common species appear on more sites than rare species. Richness in not controled
#' and scales with number of species. Note that we
#' assume no immigration / emigration.
#'
#' @examples
#' pool <- sp_pool(50)
#' define_sites_years_occ(pool = pool, n_years = 3, n_sites = 10)
define_sites_years_occ <- function(pool, n_years, n_sites,
                               rich_mean = 30, rich_sd = 5){
  #defensive programming here (i.e. check if numeric and range)
  species <- pool[[1]]
  distrib <- pool[[2]]
  nsp <- length(species)
  #Define parametres of species occurrences
  mu.a <- mean(boot::logit(distrib))
  sd.a <- sd(boot::logit(distrib))
  sd.b <- 0.001
  #Calculate species occ
  alpha <- rnorm(nsp, mean = mu.a, sd = sd.a) # species-specific intercept
  beta <- rnorm(nsp, mean = 0, sd = sd.b) #species-specific slope
  linpred <- sapply(1:n_sites, function(X) alpha + beta * X)
  pOcc <- boot::inv.logit(linpred)
  #hist(pOcc)
  Occ <- apply(pOcc, 1:2, FUN=rbinom, n=1, size=1)
  #hist(colSums(Occ), main = "richness per site") #increments with species pool
  #summary(colSums(Occ))
  #hist(rowMeans(Occ), main = "occupancy per species") #really stable.
  #summary(rowMeans(Occ))
  Occ <- as.data.frame(Occ)
  rownames(Occ) <- species
  colnames(Occ) <- paste0("site_", 1:n_sites)
  data <- reshape2::melt(t(Occ), varnames = c("siteID", "species"))
  data <- subset(data, value > 0)[,-3]
  #data
  #And then simply stack as many years as needed
  #We assume no immigration / emigration at this point. i.e. closed populations
  #But species can get extinct over time (see next functions).
  data$year <- 1 #fill first year
  base <- data
  for(i in 1:(n_years-1)){
    newdata <- base
    newdata$year <- i+1
    data <- rbind(data, newdata)
  }
  #head(data)
  data
}
