#' Create n sites sampled over t years
#'
#' This function creates for a given species pool, a data.frame of species observed per site and year.
#'
#' @param pool list, a list generated by sp_pool() containing species and ditrib
#' @param n_years Numeric, number of years
#' @param n_sites Numeric, number of sites (imagine a lattice)
#' @param rich_mean Numeric, mean species richness expected per site.
#' @param rich_sd Numeric, standard deviation of the species richness expected per site
#'
#' @return A data.frame.
#' @export
#'
#' @details Species richness per site is assumed to follow a normal distribution
#' with the provided mean and sd (Negative numbers are truncated). Species are
#' assigned to each site randomly according to its expected distribution, ensuring
#' that common species appear on more sites than rare species. Note that we
#' assume no immigration / emigration.
#'
#' @examples
#' pool <- sp_pool(50)
#' define_sites_years(pool = pool, n_years = 3, n_sites = 10)
define_sites_years_rich <- function(pool, n_years, n_sites,
                               rich_mean = 30, rich_sd = 5){
  #defensive programming here (i.e. check if numeric and range)
  species <- pool[[1]]
  distrib <- pool[[2]]
  #calculate expected richness per site
  richness <- ceiling(rnorm(n_sites, mean = rich_mean, sd = rich_sd))
  #hist(richness) #rpois possible, but a quick visual inspection of data suggest rnorm is good enough.
  #Avoid negative numbers.
  richness <- ifelse(richness < 1, yes = 1, no = richness) #not too elegant.
  #create a vector of species per site over years. We will try to use data.frames to store the outputs
  longdata <- data.frame(siteID = paste0("site_", 1:n_sites),
                         richness = richness, active = 1)
  #Asign first species
  longdata[,4] <- sample(c(0,1), nrow(longdata), replace = T, prob = c(distrib[1], 1-distrib[1]))
  colnames(longdata)[4] <- species[1]
  for(i in 2:length(species)){
    #for each species, let's distributed among sites accroding to its abundance
    temp <- subset(longdata, active == 1)
    temp[,3+i] <- sample(c(1,0), nrow(temp), replace = T, prob = c(distrib[i], 1-distrib[i]))
    colnames(temp)[3+i] <- species[i]
    longdata <- merge(longdata, temp[,c(1,3+i)], by = "siteID", all.x = TRUE, sort = F)
    longdata$active[which(rowSums(longdata[,-c(1:3)], na.rm = T) >= longdata$richness)] <- 0
  } #SLOWWW
  #check richness is good
  #all.equal(rowSums(longdata[,-c(1:3)], na.rm = T), longdata$richness)
  #check distributions makes sense
  species_occ <- colSums(longdata[,-c(1:3)], na.rm = T)
  #hist(species_occ) #still most under 20%
  #summary(species_occ)
  #summary(species_occ[-which(species_occ<1)])
  #hist(species_occ[-which(species_occ<1)]) #still most under 20%
  #length(species_occ[which(species_occ<1)]) #for 1000 sp in 100 sites, 83% never observed.
  #length(species_occ[-which(species_occ<1)])
  #now lets go to long format
  data <- reshape2::melt(longdata[,-c(2,3)], variable.name = "species")
  data <- subset(data, value > 0)[,-3]
  #data
  #And then simply stack as many years as needed
  #We assume no immigration / emigration at this point. i.e. closed populations
  #But species can get extinct over time (see next functions).
  data$year <- 1 #fill first year
  base <- data
  for(i in 1:(n_years-1)){
    newdata <- base
    newdata$year <- i+1
    data <- rbind(data, newdata)
  }
  #head(data)
  data
}



