#' Create observed abundances with detection error per site and year
#'
#' This function simulate sampling with a detection probablity per species.
#'
#' @param true_abundance A data.frame, generated by true_abundances()
#' @param sp_responses A data.frame, generated by sp_responses()
#' @param pantrap Logical, should pantraps be included?
#' @param n_pan numeric, number of pantraps deployed.
#'
#' @return A vector or data.frame.
#' @export
#'
#' @examples
#' pool <- sp_pool(50)
#' site_years <- define_sites_years(pool = pool, n_years = 3, n_sites = 10)
#' pars <- sp_responses(site_years = site_years)
#' abun <- true_abundance(rounds = 8,
#'                                  site_years = site_years,
#'                                  sp_responses = pars)
#' obs_abundance(true_abundance = abun, sp_responses = pars)
#'

##It looks like the pan trap model is identical to the transect model.
#I think this should be changed to a binomial process with n trials, where
#n is the number of pan trap locations at each site. The outcome of this process
#is then the number of traps that contain the species of interest.
obs_abundance <- function(true_abundance = NULL, sp_responses, pantrap = TRUE, n_pan = 5){
  #require(reshape)
  #set fraction of true abundance observed.
  fraction_observed <- 0.5 # we detect i.e. half the existing individuals that day
  #noise can be probably added¿?

  sim_data <- true_abundance
  pars <- sp_responses
  #placeholder to save generated data
  out <- data.frame(year = NA, siteID = NA, round = NA, species = NA, abundance = NA,
                    obs = NA, detect_pan = NA, total_pantraps = NA, presences_pan = NA)
  #expand per individual catch so each indivdual is a row
  indiv <-  reshape::untable(sim_data[,c("year", "siteID", "round", "species")],
                             num = sim_data[,c("abundance")])
  #add detectabilities (stored in pars)
  indiv_det <- merge(indiv, pars[,c("species", "detect", "detect_pan")], all.x = TRUE)
  #keep track of site names
  site_names <- unique(sim_data$siteID)
  n_years <- max(sim_data$year) #can this be misleading in any situation?
  #loop trough years
  for(k in 1:n_years){
    year_temp <- subset(indiv_det, year == k)
    #loop through sites
    for(j in 1:length(site_names)){
      #select site i
      site_temp <- subset(year_temp, siteID == site_names[j])
      #loop through rounds
      for(i in 1:max(sim_data$round)){
        sr_temp <- subset(site_temp, round == i)
        #if there are records
        if(nrow(sr_temp) > 0){
          #sample x individuals randomly prop to its detectability
          sample_size <- nrow(sr_temp)*fraction_observed #can add noise here if desired
          obs_raw <- sample(sr_temp$species, size =  sample_size,
                            replace = FALSE, prob = sr_temp$detect)
          #recover true abundance and keep detect_pan
          summary_obs_raw <- tapply(sr_temp$detect, sr_temp$species, length)
          summary_detect_raw <- tapply(sr_temp$detect_pan, sr_temp$species, max)
          #and observed abundance
          obs <- table(obs_raw)
          #rescue non sampled species
          if(length(summary_obs_raw) != length(obs)){
            mised <- summary_obs_raw[which(!names(summary_obs_raw) %in% names(obs))]
            mised[1:length(mised)] <- 0
            obs <- append(obs, values = mised)
            obs <- obs[names(summary_obs_raw)]
          }
          obs_sp <- data.frame(year = rep(k, length(summary_obs_raw)),
                               siteID = rep(site_names[j], length(summary_obs_raw)),
                               round = rep(i, length(summary_obs_raw)),
                               species = names(summary_obs_raw),
                               abundance = as.vector(summary_obs_raw),
                               obs = as.vector(obs),
                               detect_pan = as.vector(summary_detect_raw),
                               total_pantraps = NA, presences_pan = NA)
          out <- rbind(out, obs_sp)
          out <- out[-1,]
          if(pantrap){
            out$total_pantraps <- n_pan
            #sample
            for(l in 1:length(out$species)){
              #calculate probaility of detecting a species as function of sampling size
              pan_det_prob <- ifelse(out$abundance[l] * out$detect_pan[l] < 1, out$abundance[l] * out$detect_pan[l], 1)
              per_pantrap <- rbinom(n = out$total_pantraps[l], size = 1, prob = pan_det_prob)
              out$presences_pan[l] <- sum(per_pantrap)
            }
            #binomial process with n trials, where n is the number of pan trap
            #locations at each site
            #The outcome of this process is then the number of traps that contain the species of interest.
          }
        }
      }
    }
  }
  out <- out[,-7] #deleting empty first row and detect_pan to avoid confusions.
  out
}

