#' Create species responses
#'
#' This function defines for each species its phenology, typical abundance, detectablity and temporal trend.
#'
#' @param site_years A data.frame, generated by define_sites_years()
#' @param pheno_peak_mean Numeric, mean of the species phenology peak (in days from 1-365)
#' @param pheno_peak_sd Numeric, sd of the species phenology peak
#' @param pheno_range_mean Numeric, mean of the species phenology ranges
#' @param pheno_range_sd Numeric, sd of the species phenology ranges
#' @param trend_max Numeric, minimum slope of linear decline per year. Take values between 0 and infinite, with values < 1 implying declines.
#' @param trend_min Numeric, máximum slope of linear decline per year. Take values between 0 and infinite, with values < 1 implying declines.
#' @param meanlog Numeric, parameter of the lognormal distribution to generate species abundances. Default 3
#' @param sdlog Numeric, parameter of the lognormal distribution to generate species abundances. Default 0.6
#'
#' @return A data.frame.
#' @export
#'
#' @details Species phenological peak activity and phenological range are normally distributed using the provided means and sd.
#' Species peak abundances are calculated from a lognormal distribution with meanlog = 3 and sdlog = 0.8. This creates
#' abundance distributions mirroring empirical observed patterns, and within the range of the expected
#' absolute values for pollinators. Species responses are drawn from a normal distribution calculated from the the maximum and minimum
#' values provided. Finally, species detectabilities follow a beta distribution with alpha = 1 and beta = 2
#' and the probability of detecting an individual in a pantrap (p) is calculated from
#' p = 1-(1-q)^N, where q is the number of pantraps deployed and N the population abundances,
#' using TERENO project data we estimate q and N values. According to this data, p is
#' gamma-distributed with Shape = 1.221913, Rate = 140.532379 and Scale: 0.007115798.
#'
#' @examples
#' site_years <- define_sites_years(nsp = 100, n_years = 3, n_sites = 10)
#' sp_responses(site_years = site_years)
sp_responses <- function(site_years, pheno_peak_mean = 120, pheno_peak_sd = 50,
                         pheno_range_mean = 25, pheno_range_sd = 5,
                         trend_max = 1.1, trend_min = 0.9, meanlog = 3.5, sdlog = 0.6){
  #Define species responses.
  species <- unique(site_years$species)
  n_sp <- length(species)
  #Define the phenological gradient
  ming <- 1 # gradient minimum...
  maxg <- 365 # ...and maximum, in our case a year.
  locs <- seq(ming, maxg, length = 365) # gradient locations (i.e. daily resolution)

  #Define phenological peaks and variances
  opt <- rnorm(n_sp, mean = pheno_peak_mean, sd = pheno_peak_sd) # Normally distributed it's a fair assumption. However, a bimodal spring-summer distribution can be implemented if necessary
  tol <- rnorm(n_sp, mean = pheno_range_mean, sd = pheno_range_sd) # species tolerances (phenology ranges)
  opt <- ifelse(opt < 1, 10, opt)
  tol <- ifelse(tol < 1, 10, tol) #set minimum phenological span to 10 days
  opt <- ifelse(opt > 365, 365, opt)
  tol <- ifelse(tol > 200, 200, tol) #and max.
  #Define species abundances following a lognormal distribution
  h <- ceiling(rlnorm(n_sp, meanlog = meanlog, sdlog = sdlog)) # max abundances per species ->
  h <- ifelse(h > 600, 600, h)
  #hist(rlnorm(1000, meanlog = 3.5, sdlog = 0.5))
  #hist(rlnorm(1000, meanlog = 3, sdlog = 0.75))
  #hist(rlnorm(1000, meanlog = 2.5, sdlog = 1))
  #hist(rlnorm(1000, meanlog = 2, sdlog = 1.25))
  #hist(rlnorm(1000, meanlog = 1.5, sdlog = 1.5))
  #max(h) #this gives up to ~200 individuals per site of the dominant speices
  #can use this if needed: https://rdrr.io/cran/mobsim/man/sim_sad.html
  #h <- ifelse(max(h) > 20*mean(h), 20*mean(h), h) #cap maximum abundance
  #JRC asks about the possibility of an abundance-dependent assignation of phenological tolerances.

  #for debuging
  #x <- rlnorm(1214, meanlog = 3.5, sdlog = 0.6)
  #summary(x)
  #hist(x)

  #We can define also here the responses expected (i.e. trend).
  #We assume a multiplicative slope (-1 and 1) affecting the population per year.
  se <- ((trend_max - trend_min) / 2)/1.96
  #hist(rnorm(1000, 1, 0.051))
  slope <- rnorm(n_sp, mean = mean(c(trend_min, trend_max)), sd = se)
  #We assume a normal distribution of responses across species within the specified range.

  #Finally, we define species detectabilities
  #Assign to each species a detectability
  #detect <- runif(n_sp) #random. Note that when implemented, they will be weighted by species abundance.
  detect <-  rbeta(n_sp, 1, 1.5) #Let's assume detectabilities are low.
  #hist(rbeta(n_sp, 1, 1.5))
  #make species detectabilities proportional to abundances? We decided not to do it.
  #detect <- detect[order(detect)] #this would be a bit extreme option.
  #h <- h[order(h)]
  detect_pan <- rgamma(n_sp, shape = 1.221913, rate = 140.532379) #scale = 0.007115798 #Informed by TERENO data.
     #Now uncorrelated with above! This is prob of falling in a pantrap per indiv.

  #We can join this info at species level
  pars <- data.frame(species = species,  opt = round(opt, 2),
                     tol = round(tol, 2), h = h, slope = round(slope, 4),
                     detect = round(detect, 4), detect_pan = round(detect_pan, 4)) # put in a matrix
  pars
}
