#' Create a summary by year species and site
#'
#' This aggregates all rounds per year species and site
#'
#' @param eupoms Data.frame, generated by true_abundances() and obs_abundance()
#' @param var_name String, the name of the variable storing the observed abundances, which should a be numeric variable.
#'
#' @return A data.frame.
#' @export
#'
#' @examples
#' site_years <- define_sites_years(nsp = 100, n_years = 3, n_sites = 10)
#' pars <- sp_responses(site_years = site_years)
#' true_abundance <- true_abundance(n_round = 8,
#'                          site_years = site_years,
#'                          sp_responses = pars)
#' eupoms <- obs_abundance(true_abundance = true_abundance, sp_responses = pars)
#' summary_poms(eupoms)
summary_poms <- function(eupoms, var_name = "obs"){
  #require(reshape2)
  out <- reshape2::dcast(eupoms, year + siteID + species ~ "obs_abund", fun.aggregate = sum, value.var = var_name)
  out
}
