#' Create a summary by year species and site
#'
#' This aggregates all rounds per year species and site
#'
#' @param eupoms Data.frame, generated by true_abundances() and obs_abundance()
#' @param var_name String, the name of the variable storing the observed abundances, which should a be numeric variable.
#'
#' @return A data.frame.
#' @export
#'
#' @examples
#' summary_poms(eupoms)
summary_poms <- function(eupoms, var_name = "obs"){
  require(reshape2)
  out <- reshape2::dcast(eupoms, year + siteID + species ~ "obs_abund", fun.aggregate = sum, value.var = var_name)
  out
}
