#' Create true abundances per site and year
#'
#' This function calculate true abundance in each sampling round.
#'
#' @param rounds Numeric. Number of sampling rounds. Default to 8.
#' @param startmonth Numeric. Number of month starting to sample. Default to 2.
#' @param endmonth Numeric. Number of month stopping to sample. Default to 10.
#' @param site_years A data.frame, generated by define_sites_years()
#' @param sp_responses A data.frame, generated by sp_responses()
#'
#' @return A data.frame.
#' @export
#'
#' @examples
#' pool <- sp_pool(50)
#' site_years <- define_sites_years(pool = pool, n_years = 3, n_sites = 10)
#' pars <- sp_responses(site_years = site_years)
#' true_abundance(rounds = 8,
#'                site_years = site_years,
#'                sp_responses = pars)
true_abundance <- function(rounds = 8, startmonth = 2, endmonth = 10,
                           site_years = NA, sp_responses = NA){
  #require(reshape2)
  #require(coenocliner)
  #Define sampling events per year:
  data <- site_years
  pars <- sp_responses
  #Rounds are constrained from February to October.
  rounds <- seq(startmonth*30, endmonth*30, length = rounds) # gradient locations (sampling points)
  #Calculate abundande per site and year
  n_years <- max(data$year)
  site_names <- unique(data$siteID)
  #mus <- list() #store in lists if needed (do we need to keep track of this?)
  #For now we store final counts only
  simnbs <- data.frame(year = NA, siteID = NA, round = NA, species = NA, abundance = NA)
  for(j in 1:n_years){
    #select year j
    year_temp <- subset(data, year == j)
    #We add white noise to h as a function of year (yearly fluctuations)
    #And a directional noise (red noise) based on species responses.
    white_noise <- rnorm(length(pars$h), 0, 0.05) #this is very little white noise. Revisit once data is available
    pars$h_y <- pars$h * ((pars$slope + white_noise)^j) #can never get negative, just terribly small.
    for(i in 1:length(site_names)){
      #select site i
      site_temp <- subset(data, siteID == site_names[i])
      #select species present in site i
      pars_temp <- pars[which(pars$species %in% site_temp$species),]
      pars_i <- cbind(opt = pars_temp$opt, tol = pars_temp$tol, h = pars_temp$h_y)
      #create ideal community
      #mus[[i]]  <- coenocline(locs, responseModel = "gaussian", params = pars_i,
      #  expectation = TRUE)
      #plot(mus[[i]], lty = "solid", type = "l", ylim = c(0,100), xlab = "jday", ylab = "Abundance", las= 1)
      #create observed community
      simnb <- coenocliner::coenocline(rounds, responseModel = "gaussian", params = pars_i,
                          countModel = "negbin", countParams = list(alpha = 0.5))
      #transform the sim to long format
      sim <- as.data.frame(simnb) #we lose species names
      colnames(sim) <- pars_temp$species
      sim$rounds <- 1:length(rounds)
      sim_melted <- reshape2::melt(data = sim, id.vars = c("rounds"), preserve.na = T)
      sim_melted$siteID <- site_names[i]
      sim_melted$year <- j
      sim_melted <- sim_melted[,c("rounds", "variable", "value", "siteID", "year")]
      colnames(sim_melted) <- c("round", "species", "abundance", "siteID", "year")
      simnbs <- rbind(simnbs, sim_melted[,c("year", "siteID", "round", "species", "abundance")]) #CHECK!
    }
    simnbs <- simnbs[-1,]
    #head(simnbs)
  }
  #head(simnbs)
  #dim(simnbs) # 3y * 10 sites *30 sp *8 rounds <- ~ 7200
  simnbs
}
